/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */
 export const videos = [
  {
    _id: "0a5j9zh4MAA",
    channelName: "Dhruv Rathee",
    categoryName: "Current Affairs",
    title: "Ukraine vs Russia Crisis | Danger of WW3? | Dhruv Rathee",
    views: "4.4M views",
    date: "Dec 24, 2021",
    time: "19:17",
    ProfileImage: "/assets/image/Video-Image/Profile Image.jpg",
    thumbnail: "/assets/image/Video-Image/World-War3.webp",
  },
  {
    _id: "0a5j9zh178M",
    channelName: "Dhruv Rathee",
    categoryName: "Current Affairs",
    title: "What is Capitalism? | How does Money make Money? | Dhruv Rathee",
    views: "1.7M views",
    date: "Mar 18, 2021",
    time: "16:45",
    ProfileImage: "/assets/image/Video-Image/Profile Image.jpg",
    thumbnail: "/assets/image/Video-Image/Capitalism.webp",
  },
  {
    _id: "0a5j9zh130M",
    channelName: "Dhruv Rathee",
    categoryName: "Current Affairs",
    title: "Universal Basic Income | Explained by Dhruv Rathee",
    views: "1.3M views",
    date: "Dec 24, 2021",
    time: "18:33",
    ProfileImage: "/assets/image/Video-Image/Profile Image.jpg",
    thumbnail: "/assets/image/Video-Image/Flying Car.webp",
  },
  {
    _id: "0a5j9zh784M",
    channelName: "Dhruv Rathee",
    categoryName: "Current Affairs",
    title: "James Webb Space Telescope | Can it Time Travel? | Big Bang | Dhruv Rathee",
    views: "3.4M views",
    date: "Jan 08, 2020",
    time: "12:58",
    ProfileImage: "/assets/image/Video-Image/Profile Image.jpg",
    thumbnail: "/assets/image/Video-Image/Real Time Travel.webp",
  },
  {
    _id: "5a0j9zh4MAA",
    channelName: "Dhruv Rathee",
    categoryName: "Education",
    title: "Space Tourism | Jeff Bezos vs Richard Branson vs Elon Musk | Dhruv Rathee",
    views: "1.6M views",
    date: "Jul 20, 2021",
    time: "12:12",
    ProfileImage: "/assets/image/Video-Image/Profile Image.jpg",
    thumbnail: "/assets/image/Video-Image/Jeff Bezos Space.webp",
  },
  {
    _id: "5a0j9zh17AA",
    channelName: "Dhruv Rathee",
    categoryName: "Education",
    title: "Which is the Best State in India? | Dhruv Rathee Analysis on Economy, Environment, Development",
    views: "5.7M views",
    date: "Jan 6, 2018",
    time: "10:05",
    ProfileImage: "/assets/image/Video-Image/Profile Image.jpg",
    thumbnail: "/assets/image/Video-Image/Best State.webp",
  },
  {
    _id: "5a0j9zh413A",
    channelName: "Dhruv Rathee",
    categoryName: "Education",
    title: "Bitcoin in India by Dhruv Rathee | What is Bitcoin? How to buy Bitcoin? Is it legal?",
    views: "1.3M views",
    date: "Dec 24, 2021",
    time: "12:06",
    ProfileImage: "/assets/image/Video-Image/Profile Image.jpg",
    thumbnail: "/assets/image/Video-Image/Bitcoin.webp",
  },
  {
    _id: "5a0j9zh491A",
    channelName: "Dhruv Rathee",
    categoryName: "Education",
    title: "2.0 - Science behind Rajnikanth 's Movie | Mobile Phone Radiation Explained by Dhruv Rathee",
    views: "3.4M views",
    date: "Dec 05, 2018",
    time: "12:51",
    ProfileImage: "/assets/image/Video-Image/Profile Image.jpg",
    thumbnail: "/assets/image/Video-Image/Mobile Radiation.webp",
  },
  {
    _id: "9a0j9zh4wAA",
    channelName: "Dhruv Rathee",
    categoryName: "Solutions",
    title: "Singapore vs India | Education System Analysis by Dhruv Rathee",
    views: "1.1M views",
    date: "Feb 20, 2020",
    time: "12:40",
    ProfileImage: "/assets/image/Video-Image/Profile Image.jpg",
    thumbnail: "/assets/image/Video-Image/India Education.webp",
  },
  {
    _id: "9a0j9zh17tA",
    channelName: "Dhruv Rathee",
    categoryName: "Solutions",
    title: "How to Save Rivers in India by Dhruv Rathee | Can Rally for Rivers work?",
    views: "1.5M views",
    date: "Sep 19, 2017",
    time: "15:11",
    ProfileImage: "/assets/image/Video-Image/Profile Image.jpg",
    thumbnail: "/assets/image/Video-Image/Save Rivers.webp",
  },
  {
    _id: "9a0j9zh41jA",
    channelName: "Dhruv Rathee",
    categoryName: "Solutions",
    title: "How to fight Overpopulation in India by Dhruv Rathee",
    views: "1.3M views",
    date: "Jul 17, 2017",
    time: "10:01",
    ProfileImage: "/assets/image/Video-Image/Profile Image.jpg",
    thumbnail: "/assets/image/Video-Image/OverPopulation.webp",
  },
  {
    _id: "9a0j9zh49nA",
    channelName: "Dhruv Rathee",
    categoryName: "Solutions",
    title: "Water Crisis: 6 Ways to Save Yourself! | Explained by Dhruv Rathee",
    views: "797K views",
    date: "Jun 26, 2019",
    time: "14:48",
    ProfileImage: "/assets/image/Video-Image/Profile Image.jpg",
    thumbnail: "/assets/image/Video-Image/Crisis.webp",
  },
  {
    _id: "1a0j9zh0wAA",
    channelName: "Dhruv Rathee",
    categoryName: "Interview",
    title: "Prashant Bhushan Case | Interview with Dhruv Rathee",
    views: "1.1M views",
    date: "Sep 2, 2020",
    time: "12:06",
    ProfileImage: "/assets/image/Video-Image/Profile Image.jpg",
    thumbnail: "/assets/image/Video-Image/Prashant Bhushan.webp",
  },
  {
    _id: "1a0j9zh57tA",
    channelName: "Dhruv Rathee",
    categoryName: "Interview",
    title: "Flying Beast Interview: Is Air Asia Safe? | Dhruv Rathee",
    views: "3.8M views",
    date: "Jan 26, 2020",
    time: "19:24",
    ProfileImage: "/assets/image/Video-Image/Profile Image.jpg",
    thumbnail: "/assets/image/Video-Image/Air Asia.webp",
  },
  {
    _id: "1a0j9zh46jA",
    channelName: "Dhruv Rathee",
    categoryName: "Interview",
    title: "Exclusive Interview of an Indian Soldier with Dhruv Rathee | Ground Reality of Indian Jawan",
    views: "405K views",
    date: "Jun 09, 2018",
    time: "26:37",
    ProfileImage: "/assets/image/Video-Image/Profile Image.jpg",
    thumbnail: "/assets/image/Video-Image/Indian Soldier.webp",
  },
  {
    _id: "1a0j9zh59nA",
    channelName: "Dhruv Rathee",
    categoryName: "Interview",
    title: "Manish Sisodia Interview with Dhruv Rathee Part-2 | Education & Govt Schools",
    views: "597K views",
    date: "Dec 28, 2017",
    time: "24:10",
    ProfileImage: "/assets/image/Video-Image/Profile Image.jpg",
    thumbnail: "/assets/image/Video-Image/manish sisodia.webp",
  },
];
